# conf file for debug bot
username = debug
nickname = debug
hostname = undernet.org
userdescription = GNUWorld Debug Services

mode = +ik

# permit the given user -- by account login name -- to use the
# module.  You may have as many of these as you like (including none).
# This is case-insensitive.
permit_user = YourAccount
