-- "$Id: ccontrol.commands.sql,v 1.1 2001/07/26 20:12:39 mrbean_ Exp $"

-- Fills the commands table with the default values 
-- Note: DO NOT EDIT THIS FILE BY HAND!
-- 	 THESE ARE JUST DEFAULT VALUES 
--	 USE THE COMMANDS COMMAND TO CHANGE THEM

-- Last Updated : 26/07/01 |MrBean|

Delete from commands;

INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('ACCESS','ACCESS',1,'n','n','t',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('HELP','HELP',1,'n','n','t',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('LOGIN','LOGIN',0,'n','t','t',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('DEAUTH','DEAUTH',1,'n','n','t',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('NEWPASS','NEWPASS',1,'n','n','t',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('MODE','MODE',2,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('OP','OP',2,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('DEOP','DEOP',2,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('MODERATE','MODERATE',2,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('UNMODERATE','UNMODERATE',2,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('INVITE','INVITE',4,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('JUPE','JUPE',8,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('GLINE','GLINE',16,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('REMGLINE','REMGLINE',16,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('SCANGLINE','SCANGLINE',16,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('REMOPERCHAN','REMOPERCHAN',32,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('ADDOPERCHAN','ADDOPERCHAN',32,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('LISTOPERCHANS','LISTOPERCHANS',32,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('CHANINFO','CHANINFO',64,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('WHOIS','WHOIS',128,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('ADDUSER','ADDUSER',256,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('REMUSER','REMUSER',256,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('MODUSER','MODUSER',256,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('TRANSLATE','TRANSLATE',512,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('KICK','KICK',1024,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('ADDCOMMAND','ADDCOMMAND',2048,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('REMCOMMAND','REMCOMMAND',2048,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('SUSPEND','SUSPEND',4096,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('UNSUSPEND','UNSUSPEND',4096,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('CLEARCHAN','CLEARCHAN',8192,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('LISTHOSTS','LISTHOSTS',256,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('ADDSERVER','ADDSERVER',16384,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('LEARNNET','LEARNNET',16384,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('REMSERVER','REMSERVER',16384,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('CHECKNET','CHECKNET',16384,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('LASTCOM','LASTCOM',32768,'n','n','t',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('FROCEGLINE','FORCEGLINE',65535,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('EXCEPTIONS','EXCEPTIONS',131072,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('LISTIGNORES','LISTIGNORES',262144,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('REMIGNORE','REMIGNORE',524288,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('LIST','LIST',1048576,'n','n','n',1);
INSERT INTO COMMANDS (Name,RealName,Flags,isDisabled,NeedOp,NoLog,MinLevel) VALUES ('COMMANDS','COMMANDS',2097152,'n','n','n',1);







