-- Autogenerated dump on Wed Apr  2 09:02:42 UTC 2025

COPY languages FROM stdin;
1	EN	English	31337	0
2	FR	Fran�ais	31337	0
3	DK	Danish	31337	0
4	NL	Dutch	31337	0
5	DE	German	31337	0
6	PT	Portuguese	31337	0
7	IT	Italian	31337	0
8	RO	Romanian	31337	0
9	CA	Catalan	31337	0
10	ES	Spanish	31337	0
11	HU	Hungarian	31337	0
12	TR	Turkce	31337	0
13	NO	Norsk	31337	0
14	AR	Arabic	31337	0
15	IL	Hebrew	31337	0
16	MK	Makedonski	31337	0
17	EA	Easter	31337	0
18	HA	Halloween	31337	0
19	GR	Greek	31337	0
20	SV	Svenska	31337	0
21	CH	Christmas	31337	0
22	SW	StarWars	31337	0
23	WW	Werewolf	31337	0
24	GOT	GameOfThrones	31337	0
25	ASS	ASSHOLE	31337	0
\.
