-- Autogenerated dump on Wed Apr  2 09:02:42 UTC 2025

COPY languages FROM stdin;
1	EN	English	31337
2	FR	Français	31337
3	DK	Danish	31337
4	NL	Dutch	31337
5	DE	German	31337
6	PT	Portuguese	31337
7	IT	Italian	31337
8	RO	Romanian	31337
9	CA	Catalan	31337
10	ES	Spanish	31337
11	HU	Hungarian	31337
12	TR	Turkce	31337
13	NO	Norsk	31337
14	AR	Arabic	31337
15	IL	Hebrew	31337
16	MK	Makedonski	31337
17	EA	Easter	31337
18	HA	Halloween	31337
19	GR	Greek	31337
20	SV	Svenska	31337
21	CH	Christmas	31337
22	SW	StarWars	31337
23	WW	Werewolf	31337
24	GOT	GameOfThrones	31337
25	ASS	ASSHOLE	31337
\.
