#!/bin/sh

# MrIron & Empus -- 17 October 2024
# Purpose of this script is to make dumps from the languages, translations and help tables.

database=cservice
header="-- Autogenerated dump on $(date)"

echo "Setting client encoding to SQL_ASCII...";
export PGCLIENTENCODING=SQL_ASCII

echo "Dumping languages table...";
{
  echo "$header";
  echo "";
  echo "-- Zap everything!"
  echo "DELETE FROM languages;"
  echo "";
  echo "COPY languages FROM stdin;";
  psql -d $database -c "COPY (SELECT * FROM languages ORDER BY id) TO STDOUT;"
  echo "\.";
} > cservice.languages.sql

echo "Dumping translations table...";
{
  echo "-- Language Definition Table for CMaster Undernet channel services.";
  echo "$header";
  echo "-- Zap everything!"
  echo "DELETE FROM translations;"
  echo "";
  echo "COPY translations FROM stdin;";
  psql -d $database -c "COPY (SELECT * FROM translations ORDER BY language_id, response_id) TO STDOUT;"
  echo "\.";
} > cservice.translations.sql

echo "Dumping help table...";
{
  echo "$header";
  echo "-- Zap everything!"
  echo "DELETE FROM help;"
  echo "";
  echo "COPY help FROM stdin;";
  psql -d $database -c "COPY (SELECT * FROM help ORDER BY language_id, topic) TO STDOUT;"
  echo "\.";
} > cservice.help.sql

echo "Done!"
